# This is a generated file DO NOT EDIT
# generated by data/build_types.pl using data/Types.tt2
#
# Any changes should be made to data/Types.tt2
# followed by running data/build_types.pl
#
###################################################

package Games::Lacuna::Client::Types;

use strict;
use warnings;
use List::MoreUtils qw(any);

require Exporter;

our @ISA = qw(Exporter);
our @EXPORT = qw( meta_type food_types ore_types );
our %EXPORT_TAGS = (
    list => [qw( food_types ore_types )],
    all  => [@EXPORT],
);

{
    my @food = qw( algae apple bean beetle bread burger chip cheese cider corn fungus lapis meal milk pancake pie potato root shake soup syrup wheat );
    sub food_types {
        return @food;
    }
}

{
    my @ore = qw( anthracite bauxite beryl chalcopyrite chromite fluorite galena goethite gold gypsum halite kerogen magnetite methane monazite rutile sulfur trona uraninite zircon );
    sub ore_types {
        return @ore;
    }
}

{
    my %meta_types = (
        command => [qw(
            Archaeology
            Development
            Embassy
            Intelligence
            Network19
            Observatory
            Park
            PlanetaryCommand
            Security
            Shipyard
            SpacePort
            Trade
            Transporter
            Capitol
            CloakingLab
            Espionage
            GasGiantLab
            GasGiantPlatform
            GeneticsLab
            MissionCommand
            MunitionsLab
            Oversight
            PilotTraining
            Propulsion
            Stockpile
            TerraformingLab
            TerraformingPlatform
            University
        )],
        energy => [qw(
            Fission
            Fusion
            Geo
            HydroCarbon
            Singularity
            WasteEnergy
        )],
        food => [qw(
            Algae
            Apple
            Bean
            Beeldeban
            Bread
            Burger
            Cheese
            Chip
            Cider
            Corn
            CornMeal
            Dairy
            Denton
            Lapis
            Malcud
            Pancake
            Pie
            Potato
            Shake
            Soup
            Syrup
            Wheat
        )],
        glyph => [qw(
            Crater
            CrashedShipSite
            EssentiaVein
            GeoThermalVent
            InterDimensionalRift
            KalavianRuins
            Lake
            Lagoon
            LibraryOfJith
            Grove
            MassadsHenge
            NaturalSpring
            OracleOfAnid
            RockyOutcrop
            Ravine
            Sand
            TempleOfTheDrajilites
            Volcano
        )],
        happiness => [qw(
            Entertainment
            LuxuryHousing
        )],
        ore => [qw(
            Mine
            OreRefinery
            WasteDigester
            MiningMinistry
        )],
        storage => [qw(
            WasteSequestration
            EnergyReserve
            WaterStorage
            FoodReserve
            OreStorage
        )],
        waste => [qw(
            WasteTreatment
            WasteRecycling
        )],
        water => [qw(
            WaterProduction
            WaterPurification
            WaterReclamation
        )],
    );

    sub meta_type {
        my( $type ) = @_;
        return unless $type;
        for my $k ( keys %meta_types ){
            if( any {$_ eq $type} @{$meta_types{$k}} ){
                return $k;
            }
        }
        return;
    }
}
1;

__END__

=head1 NAME

Games::Lacuna::Client::Types

=head1 SYNOPSIS

    use Games::Lacuna::Client::Types;

=head1 FUNCTIONS

=over 4

=item meta_type

=item food_types

=item ore_types

=back

=cut
